### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by funkotron** [lyz-code/blue-book#21]
Dear @lyz-code 

I've created a repo with some ideas for freedom of information that I hope you might be interested in (from reading your blue book I saw you're into Freedom of Knowledge): https://github.com/funkotron/tree

The idea is to augment mkdocs to make it easier for an average user to use.

This includes Navigation wise (use dot notation in filenames or folder structure to build navigation), internal Linking (double bracket notation for linking), using a pipeline to convert webpages and PDFs to markdown so they can be archived and referenced, and Installation (using a PyInstaller) and publishing to IPFS.

Please take a look and feel free to give any feedback/review/ideas or use any of the examples to build an actual functional version :) Apologies for my poor and messy code, I hope it makes sense!

I'd love to get this working with either PyInstaller or a docker service like this https://github.com/bluxmit/alnoda-workspaces/tree/main/workspaces/mkdocs-magicspace so that more people could publish their own sites, build up and connect ideas they've read across the web or in PDFs and write their own articles.

Thank you

**Comment by lyz-code** [comment]
Hi @funkotron , your project looks superb!

I'll try to save some time this week to take a full dive into the code and I'll come back with some feedback for sure :)

**Comment by lyz-code** [comment]
Hi @funkotron I finally  never got the chance to review your project. I'm so sorry I kept you waiting :(

I've looked at your repos and I was not able to find it anymore, I hope you didn't give up!
