### ISSUE TITLE
Hey! BTN Member

### ISSUE THREAD

**Issue by shakil1819** [lyz-code/blue-book#29]
Hello there,
Recently i have researched and found that you are a member of top tier tracker BTN [BroadcasTheNet] . I have excellent ratio proofs , speedtest proofs and experience with private trackers. Can you give me an invite ? If yes,  then it would be great really. I have many invitations from differetnt trackers and i am really in need of getting into BTN tracker

my email :  U63k5@protonmail.com

Thank you for your patience

-Regards

**Comment by lyz-code** [comment]
Hi @shakil1819 thanks for reaching out. I'm afraid I'm not part of that tracker. Even if I were I wouldn't give invites away to people that I don't know, I hope you understand the underlying reasons.
