### ISSUE TITLE
Ryot and Jellyfin scrobbling

### ISSUE THREAD

**Issue by IgnisDa** [lyz-code/blue-book#32]
Hello! I came across [this](https://lyz-code.github.io/blue-book/mediatracker/?h=ryot#cant-find-a-book) section in the Bluebook.

> but it still doesn't have a [jellyfin scrobbler](https://github.com/IgnisDa/ryot/issues/187).

As of writing this comment, Ryot supports Jellyfin. Or are there any other features missing?

**Comment by lyz-code** [comment]
Hi @IgnisDa , I haven't yet had time to try the scrobbler you proposed [here](https://github.com/IgnisDa/ryot/pull/195). I'll update the comment to:

> [Ryot](https://github.com/IgnisDa/ryot) seems to work better with books, it also has a [jellyfin scrobbler](https://github.com/IgnisDa/ryot/pull/195), although it's not [yet stable](https://github.com/IgnisDa/ryot/issues/187).

Do  you agree with it?

There are other UI tweaks that is preventing me from migrating to ryot, but I'll open them as issues in your repo.

Out of curiosity, how did you end up in that article?!

**Comment by IgnisDa** [comment]
> Do you agree with it?

I am not sure what you mean by "better" here. Both download data from Openlibrary (though Ryot can also get metadata from Google Books).

> Out of curiosity, how did you end up in that article?

You opened an issue on MediaTracker repo and I liked your profile picture (I love Death Note too) and I clicked on the most starred repo.

**Comment by lyz-code** [comment]
> I am not sure what you mean by "better" here. Both download data from Openlibrary (though Ryot can also get metadata from Google Books).

You're right, maybe I hit a bug on mediatracker, but when I wrote those lines I was not able to find some books on mediatracker that I was able to fetch on ryot. I'm able to find them though so I'll amend.

Thanks for taking the time to open the issue <3
