### ISSUE TITLE
This repository is the most inspiring space I've been in a while

### ISSUE THREAD

**Issue by mbbroberg** [lyz-code/blue-book#34]
Hi @lyz-code – you can promptly close this issue, but I had to say that I am incredibly inspired by your digital garden. 

I've been in a creative block of late, finding so much I enjoy learning and the urge to share it, but my previous "season's" approach of episodic content through blog or tweet doesn't give the same sense of satisfaction. Wandering through this welcoming space gave me immediate joy in a way I've learn to pursue. Thank you for sharing this.

**Comment by lyz-code** [comment]
Hi @mbbroberg thank you for your kind words <3. 

It fills me with joy to see that people are actually enjoying my digital garden. As I don't use any tracking tool I have no way of knowing if it's used at all. 

Gestures like this issue give me energy to keep on going :). I hope that the digital garden seed has taken root in yourself and we can soon have another gardener in [Best of digital gardens](https://github.com/lyz-code/best-of-digital-gardens)
